# Generated by Django 5.2.10 on 2026-02-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='recruiter_decision',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='swipe',
            name='action',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('REJECT', 'REJECT')], max_length=10),
        ),
    ]
